version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes_from:
            - app
        depends_on:
            - php
        links:
            - php
        container_name: "conteneur_nginx"
    php:
        build: ./php
        volumes_from:
            - app
        expose:
            - "9000"
        links:
            - mysql
        container_name: "conteneur_php"
    mysql:
        image: mysql
        expose:
            - "3306"
        container_name: "conteneur_mysql"
        volumes_from:
            - data
        environment:
            MYSQL_DATABASE: dev-database
            MYSQL_USER: evans
            MYSQL_PASSWORD: evans
            MYSQL_ROOT_PASSWORD: evans@root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8080:80"
        container_name: "conteneur_phpmyadmin"
    mongo:
        image: mongo
        expose:
            - "27017"
        container_name: "conteneur_mongo"
    app:
        image: "php:7.1-fpm"
        volumes:
            - /home/docker/app:/var/www/html
    data:
        image: "php:7.1-fpm"
        volumes:
            - /home/docker/db/mysql:/var/lib/mysql
